-- Easylearn Institute Progress 15
-- SaaS plans, institute subscriptions, manual payment approval and platform audit log.

create table if not exists public.subscription_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  monthly_price numeric(12,2) not null default 0,
  yearly_price numeric(12,2) not null default 0,
  max_students integer,
  max_teachers integer,
  features jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  institute_id uuid not null references public.institutes(id) on delete cascade,
  plan_id uuid not null references public.subscription_plans(id),
  status text not null default 'trial' check (status in ('trial','active','past_due','suspended','cancelled','expired')),
  billing_cycle text not null default 'monthly' check (billing_cycle in ('monthly','yearly')),
  starts_at timestamptz not null default now(),
  trial_ends_at timestamptz,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists uq_subscriptions_one_live_per_institute
on public.subscriptions(institute_id)
where status in ('trial','active','past_due');
create index if not exists idx_subscriptions_institute on public.subscriptions(institute_id);

create table if not exists public.subscription_payments (
  id uuid primary key default gen_random_uuid(),
  institute_id uuid not null references public.institutes(id) on delete cascade,
  subscription_id uuid not null references public.subscriptions(id) on delete cascade,
  requested_plan_id uuid references public.subscription_plans(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0),
  method text not null check (method in ('Cash','bKash','Nagad','Rocket','Bank')),
  transaction_reference text,
  payment_date date not null default current_date,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  note text,
  created_at timestamptz not null default now()
);
alter table public.subscription_payments add column if not exists requested_plan_id uuid references public.subscription_plans(id) on delete set null;

create index if not exists idx_subscription_payments_institute on public.subscription_payments(institute_id, payment_date desc);

create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  institute_id uuid references public.institutes(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_logs_institute_created on public.audit_logs(institute_id, created_at desc);

insert into public.subscription_plans (name, monthly_price, yearly_price, max_students, max_teachers, features)
values
 ('Trial',0,0,100,10,'{"attendance":true,"fees":true,"academics":true,"reports":true,"portals":true}'::jsonb),
 ('Basic',999,9990,300,25,'{"attendance":true,"fees":true,"academics":true,"reports":true,"portals":true}'::jsonb),
 ('Standard',1999,19990,1000,75,'{"attendance":true,"fees":true,"academics":true,"reports":true,"portals":true,"notifications":true}'::jsonb),
 ('Premium',3999,39990,null,null,'{"attendance":true,"fees":true,"academics":true,"reports":true,"portals":true,"notifications":true,"priority_support":true}'::jsonb)
on conflict (name) do nothing;

create or replace function public.is_platform_admin()
returns boolean language sql security definer set search_path=public stable as $$
  select exists(select 1 from public.platform_admins where user_id = auth.uid());
$$;
grant execute on function public.is_platform_admin() to authenticated;

create or replace function public.ensure_trial_subscription()
returns uuid language plpgsql security definer set search_path=public as $$
declare
  v_inst uuid;
  v_sub uuid;
  v_plan uuid;
begin
  v_inst := public.ensure_my_institute();
  select id into v_sub from public.subscriptions where institute_id=v_inst and status in ('trial','active','past_due') order by created_at desc limit 1;
  if v_sub is not null then return v_sub; end if;
  select id into v_plan from public.subscription_plans where name='Trial' limit 1;
  insert into public.subscriptions(institute_id,plan_id,status,billing_cycle,starts_at,trial_ends_at,current_period_start,current_period_end)
  values(v_inst,v_plan,'trial','monthly',now(),now()+interval '30 days',now(),now()+interval '30 days') returning id into v_sub;
  return v_sub;
end;
$$;
grant execute on function public.ensure_trial_subscription() to authenticated;

create or replace function public.submit_subscription_payment(p_subscription_id uuid,p_requested_plan_id uuid,p_amount numeric,p_method text,p_reference text,p_payment_date date,p_note text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_inst uuid; v_id uuid;
begin
  v_inst := public.get_my_institute_id();
  if v_inst is null then raise exception 'Institute not found'; end if;
  if not exists(select 1 from public.subscriptions where id=p_subscription_id and institute_id=v_inst) then raise exception 'Subscription not found'; end if;
  if p_requested_plan_id is not null and not exists(select 1 from public.subscription_plans where id=p_requested_plan_id and status='active') then raise exception 'Plan not found'; end if;
  if p_amount <= 0 then raise exception 'Amount must be positive'; end if;
  insert into public.subscription_payments(institute_id,subscription_id,requested_plan_id,amount,method,transaction_reference,payment_date,note)
  values(v_inst,p_subscription_id,p_requested_plan_id,p_amount,p_method,p_reference,p_payment_date, p_note) returning id into v_id;
  insert into public.audit_logs(institute_id,actor_user_id,action,entity_type,entity_id,details)
  values(v_inst,auth.uid(),'subscription_payment_submitted','subscription_payment',v_id::text,jsonb_build_object('amount',p_amount,'method',p_method));
  return v_id;
end;
$$;
grant execute on function public.submit_subscription_payment(uuid,uuid,numeric,text,text,date,text) to authenticated;

create or replace function public.review_subscription_payment(p_payment_id uuid,p_decision text,p_note text default null)
returns boolean language plpgsql security definer set search_path=public as $$
declare p public.subscription_payments%rowtype;
begin
  if not public.is_platform_admin() then raise exception 'Platform admin access required'; end if;
  if p_decision not in ('approved','rejected') then raise exception 'Invalid decision'; end if;
  select * into p from public.subscription_payments where id=p_payment_id;
  if p.id is null then raise exception 'Payment not found'; end if;
  update public.subscription_payments set status=p_decision,reviewed_by=auth.uid(),reviewed_at=now(),note=coalesce(p_note,note) where id=p_payment_id;
  if p_decision='approved' then
    update public.subscriptions set plan_id=coalesce(p.requested_plan_id,plan_id), status='active',current_period_start=greatest(coalesce(current_period_start,now()),now()),current_period_end=case when billing_cycle='yearly' then now()+interval '1 year' else now()+interval '1 month' end,updated_at=now() where id=p.subscription_id;
  end if;
  insert into public.audit_logs(institute_id,actor_user_id,action,entity_type,entity_id,details)
  values(p.institute_id,auth.uid(),'subscription_payment_reviewed','subscription_payment',p_payment_id::text,jsonb_build_object('decision',p_decision));
  return true;
end;
$$;
grant execute on function public.review_subscription_payment(uuid,text,text) to authenticated;

create or replace function public.refresh_subscription_status()
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.subscriptions set status='expired',updated_at=now()
  where status='trial' and trial_ends_at is not null and trial_ends_at < now();
  update public.subscriptions set status='expired',updated_at=now()
  where status='active' and current_period_end is not null and current_period_end < now();
end;
$$;
grant execute on function public.refresh_subscription_status() to authenticated;

alter table public.subscription_plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.subscription_payments enable row level security;
alter table public.platform_admins enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "Plans readable by authenticated" on public.subscription_plans;
create policy "Plans readable by authenticated" on public.subscription_plans for select to authenticated using (status='active' or public.is_platform_admin());

drop policy if exists "Members view own subscriptions" on public.subscriptions;
create policy "Members view own subscriptions" on public.subscriptions for select to authenticated using (institute_id=public.get_my_institute_id() or public.is_platform_admin());
drop policy if exists "Platform admins manage subscriptions" on public.subscriptions;
create policy "Platform admins manage subscriptions" on public.subscriptions for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());

drop policy if exists "Members view own subscription payments" on public.subscription_payments;
create policy "Members view own subscription payments" on public.subscription_payments for select to authenticated using (institute_id=public.get_my_institute_id() or public.is_platform_admin());
drop policy if exists "Platform admins manage subscription payments" on public.subscription_payments;
create policy "Platform admins manage subscription payments" on public.subscription_payments for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());

drop policy if exists "Platform admins view platform admins" on public.platform_admins;
create policy "Platform admins view platform admins" on public.platform_admins for select to authenticated using (user_id=auth.uid() or public.is_platform_admin());

drop policy if exists "Members view own audit logs" on public.audit_logs;
create policy "Members view own audit logs" on public.audit_logs for select to authenticated using (institute_id=public.get_my_institute_id() or public.is_platform_admin());
drop policy if exists "Platform admins manage audit logs" on public.audit_logs;
create policy "Platform admins manage audit logs" on public.audit_logs for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());
